### ISSUE TITLE
WA DOR just changed the URL for the tax lookup tool

### ISSUE THREAD

**Issue by mamstergrub** [jamonholmgren/active_tax#4]
It's now http://rateservice.dor.wa.gov/text?addr=the%20address&city=Seattle&zip=98102

I've never forked a project before but I could figure it out and make a pull request if you like. Thanks for a great gem!

**Comment by mamstergrub** [comment]
And I went ahead and submitted the request. Thanks again.

**Comment by jamonholmgren** [comment]
@mamstergrub Nice! I didn't know anyone else was using this. :) Will check your PR out.

**Comment by mamstergrub** [comment]
Oh, it's really useful. I run a subscription service that's consider a sale of digital goods by the DOR, so I have to analyze a few hundred records every quarter and I'm too cheap to pay Avalara or someone to do it.

**Comment by jamonholmgren** [comment]
Fixed by @mamstergrub in #5 , thank you!! 👍 :tada: 💯 

[Released as 1.0.0](https://github.com/jamonholmgren/active_tax/releases/tag/v1.0.0) -- also :tada:
