### ISSUE TITLE
ActiveTax times out with an incomplete request

### ISSUE THREAD

**Issue by mamstergrub** [jamonholmgren/active_tax#8]
I accidentally made an ActiveTax object with the following attributes:

```
tax = ActiveTax::Tax.new ( {
  city: "Seattle",
  state: "WA",
  zip: "98102"
} )
```

i.e., I forgot the address field. When I queried the object, the code hung for a long time before timing out. I think it should probably throw an exception in this case, but I'm not sure. I mean, really what should happen is that the state API should immediately return an error, but apparently it's not. Could you please look into this? It took me an embarrassing long time to figure it out!

**Comment by jamonholmgren** [comment]
Yeah, that seems like an issue! I'll look into it.

**Comment by jamonholmgren** [comment]
The state API is hanging (runtime error) too. http://webgis.dor.wa.gov/webapi/AddressRates.aspx/text?output=text&addr=&city=Tumwater&zip=98501

I'll add some code to catch this.

**Comment by jamonholmgren** [comment]
Can you review #9 @mamstergrub ?
